package com.hynee.entity;
// Generated Jul 5, 2023, 11:01:33 AM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.MapsId;
import jakarta.persistence.Table;

import lombok.ToString;

/**
 * DetailProduct generated by hbm2java
 */
@Entity
@Table(name = "DETAIL_PRODUCT", schema = "dbo", catalog = "HYNEE")
@ToString
public class DetailProduct {

	private DetailProductId id;
	private Product product;
	private Detail detail;

	public DetailProduct() {
	}

	public DetailProduct(DetailProductId id, Product product, Detail detail) {
		this.id = id;
		this.product = product;
		this.detail = detail;
	}

	@EmbeddedId
	public DetailProductId getId() {
		return this.id;
	}

	public void setId(DetailProductId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@MapsId("productId")
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@MapsId("detailId")
	@JoinColumn(name = "detail_id", nullable = false)
	public Detail getDetail() {
		return this.detail;
	}

	public void setDetail(Detail detail) {
		this.detail = detail;
	}

}
