package com.hynee.entity;
// Generated Jul 5, 2023, 11:01:33 AM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * FeedbackId generated by hbm2java
 */
@Embeddable
public class FeedbackId {

	private String productId;
	private String userPhone;

	public FeedbackId() {
	}

	public FeedbackId(String productId, String userPhone) {
		this.productId = productId;
		this.userPhone = userPhone;
	}

	@Column(name = "product_id", nullable = false, length = 36)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	@Column(name = "user_phone", nullable = false, length = 10)
	public String getUserPhone() {
		return this.userPhone;
	}

	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FeedbackId))
			return false;
		FeedbackId castOther = (FeedbackId) other;

		return ((this.getProductId() == castOther.getProductId()) || (this.getProductId() != null
				&& castOther.getProductId() != null && this.getProductId().equals(castOther.getProductId())))
				&& ((this.getUserPhone() == castOther.getUserPhone()) || (this.getUserPhone() != null
						&& castOther.getUserPhone() != null && this.getUserPhone().equals(castOther.getUserPhone())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getProductId() == null ? 0 : this.getProductId().hashCode());
		result = 37 * result + (getUserPhone() == null ? 0 : this.getUserPhone().hashCode());
		return result;
	}

}
