package com.hynee.entity;
// Generated Jul 5, 2023, 11:01:33 AM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.ToString;

/**
 * Image generated by hbm2java
 */
@Entity
@Table(name = "IMAGE", schema = "dbo", catalog = "HYNEE")
@ToString
public class Image  {

	private String imageId;
	private Product product;

	public Image() {
	}

	public Image(String imageId, Product product) {
		this.imageId = imageId;
		this.product = product;
	}

	@Id

	@Column(name = "image_id", unique = true, nullable = false)
	public String getImageId() {
		return this.imageId;
	}

	public void setImageId(String imageId) {
		this.imageId = imageId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

}
