package com.hynee.entity;
// Generated Jul 5, 2023, 11:01:33 AM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * InvoiceDetailId generated by hbm2java
 */
@Embeddable
public class InvoiceDetailId {

	private String invoiceId;
	private String productId;
	private Integer invoiceDtPrice;
	private int invoiceDtQuantity;

	public InvoiceDetailId() {
	}

	public InvoiceDetailId(String invoiceId, String productId, int invoiceDtQuantity) {
		this.invoiceId = invoiceId;
		this.productId = productId;
		this.invoiceDtQuantity = invoiceDtQuantity;
	}

	public InvoiceDetailId(String invoiceId, String productId, Integer invoiceDtPrice, int invoiceDtQuantity) {
		this.invoiceId = invoiceId;
		this.productId = productId;
		this.invoiceDtPrice = invoiceDtPrice;
		this.invoiceDtQuantity = invoiceDtQuantity;
	}

	@Column(name = "invoice_id", nullable = false, length = 36)
	public String getInvoiceId() {
		return this.invoiceId;
	}

	public void setInvoiceId(String invoiceId) {
		this.invoiceId = invoiceId;
	}

	@Column(name = "product_id", nullable = false, length = 36)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	@Column(name = "invoice_DT_price")
	public Integer getInvoiceDtPrice() {
		return this.invoiceDtPrice;
	}

	public void setInvoiceDtPrice(Integer invoiceDtPrice) {
		this.invoiceDtPrice = invoiceDtPrice;
	}

	@Column(name = "invoice_DT_quantity", nullable = false)
	public int getInvoiceDtQuantity() {
		return this.invoiceDtQuantity;
	}

	public void setInvoiceDtQuantity(int invoiceDtQuantity) {
		this.invoiceDtQuantity = invoiceDtQuantity;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InvoiceDetailId))
			return false;
		InvoiceDetailId castOther = (InvoiceDetailId) other;

		return ((this.getInvoiceId() == castOther.getInvoiceId()) || (this.getInvoiceId() != null
				&& castOther.getInvoiceId() != null && this.getInvoiceId().equals(castOther.getInvoiceId())))
				&& ((this.getProductId() == castOther.getProductId()) || (this.getProductId() != null
						&& castOther.getProductId() != null && this.getProductId().equals(castOther.getProductId())))
				&& ((this.getInvoiceDtPrice() == castOther.getInvoiceDtPrice())
						|| (this.getInvoiceDtPrice() != null && castOther.getInvoiceDtPrice() != null
								&& this.getInvoiceDtPrice().equals(castOther.getInvoiceDtPrice())))
				&& (this.getInvoiceDtQuantity() == castOther.getInvoiceDtQuantity());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getInvoiceId() == null ? 0 : this.getInvoiceId().hashCode());
		result = 37 * result + (getProductId() == null ? 0 : this.getProductId().hashCode());
		result = 37 * result + (getInvoiceDtPrice() == null ? 0 : this.getInvoiceDtPrice().hashCode());
		result = 37 * result + this.getInvoiceDtQuantity();
		return result;
	}

}
