package com.hynee.entity;
// Generated Jul 5, 2023, 11:01:33 AM by Hibernate Tools 4.3.6.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.ToString;

/**
 * InvoiceDetail generated by hbm2java
 */
@Entity
@ToString
@Table(name = "INVOICE_DETAIL", schema = "dbo", catalog = "HYNEE")
public class InvoiceDetail  {

	private InvoiceDetailId id;
	private Invoice invoice;
	private Product product;

	public InvoiceDetail() {
	}

	public InvoiceDetail(InvoiceDetailId id, Invoice invoice, Product product) {
		this.id = id;
		this.invoice = invoice;
		this.product = product;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "invoiceId", column = @Column(name = "invoice_id", nullable = false, length = 36)),
			@AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false, length = 36)),
			@AttributeOverride(name = "invoiceDtPrice", column = @Column(name = "invoice_DT_price")),
			@AttributeOverride(name = "invoiceDtQuantity", column = @Column(name = "invoice_DT_quantity", nullable = false)) })
	public InvoiceDetailId getId() {
		return this.id;
	}

	public void setId(InvoiceDetailId id) {
		this.id = id;
	}
	
	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "invoice_id", nullable = false, insertable = false, updatable = false)
	public Invoice getInvoice() {
		return this.invoice;
	}

	public void setInvoice(Invoice invoice) {
		this.invoice = invoice;
	}
	
	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

}
