package com.hynee.entity;
// Generated Jul 5, 2023, 11:01:33 AM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.hibernate.annotations.Nationalized;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "USERS", schema = "dbo", catalog = "HYNEE")
public class Users {

	private String userPhone;
	private String userFullname;
	private String userPassword;
	private boolean userRole;
	private String userGmail;
	private String userImage;
	private Date userCreateDate;
	private Boolean userStatus;
	private Set<Invoice> invoices = new HashSet<Invoice>(0);
	private Set<Feedback> feedbacks = new HashSet<Feedback>(0);

	public Users() {
	}

	public Users(String userPhone, String userFullname, String userPassword, boolean userRole) {
		this.userPhone = userPhone;
		this.userFullname = userFullname;
		this.userPassword = userPassword;
		this.userRole = userRole;
	}

	public Users(String userPhone, String userFullname, String userPassword, boolean userRole, String userGmail,
			String userImage, Date userCreateDate, Boolean userStatus, Set<Invoice> invoices, Set<Feedback> feedbacks) {
		this.userPhone = userPhone;
		this.userFullname = userFullname;
		this.userPassword = userPassword;
		this.userRole = userRole;
		this.userGmail = userGmail;
		this.userImage = userImage;
		this.userCreateDate = userCreateDate;
		this.userStatus = userStatus;
		this.invoices = invoices;
		this.feedbacks = feedbacks;
	}

	@Id

	@Column(name = "user_phone", unique = true, nullable = false, length = 10)
	public String getUserPhone() {
		return this.userPhone;
	}

	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	@Column(name = "user_fullname", nullable = false)
	@Nationalized
	public String getUserFullname() {
		return this.userFullname;
	}

	public void setUserFullname(String userFullname) {
		this.userFullname = userFullname;
	}

	@Column(name = "user_password", nullable = false, length = 60)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	@Column(name = "user_role", nullable = false)
	public boolean isUserRole() {
		return this.userRole;
	}

	public void setUserRole(boolean userRole) {
		this.userRole = userRole;
	}

	@Column(name = "user_gmail", length = 50)
	public String getUserGmail() {
		return this.userGmail;
	}

	public void setUserGmail(String userGmail) {
		this.userGmail = userGmail;
	}

	@Column(name = "user_image")
	public String getUserImage() {
		return this.userImage;
	}

	public void setUserImage(String userImage) {
		this.userImage = userImage;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "user_createDate", length = 10)
	public Date getUserCreateDate() {
		return this.userCreateDate;
	}

	public void setUserCreateDate(Date userCreateDate) {
		this.userCreateDate = userCreateDate;
	}

	@Column(name = "user_status")
	public Boolean getUserStatus() {
		return this.userStatus;
	}

	public void setUserStatus(Boolean userStatus) {
		this.userStatus = userStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Invoice> getInvoices() {
		return this.invoices;
	}

	public void setInvoices(Set<Invoice> invoices) {
		this.invoices = invoices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Feedback> getFeedbacks() {
		return this.feedbacks;
	}

	public void setFeedbacks(Set<Feedback> feedbacks) {
		this.feedbacks = feedbacks;
	}

}
