USE master
CREATE DATABASE HYNEE
go
USE HYNEE

CREATE TABLE USERS
(
	user_phone VARCHAR(10) PRIMARY KEY, 
	user_fullname NVARCHAR(30) NOT NULL,
	user_password VARCHAR(60) NOT NULL,
	user_role BIT NOT NULL,
	user_gmail VARCHAR(50),
	user_image VARCHAR(255),
	user_createDate Date DEFAULT GETDATE(),
	user_status BIT
)

CREATE TABLE CATEGORY
(
	category_id VARCHAR(10) PRIMARY KEY,
	category_name NVARCHAR(50) NOT NULL
)

CREATE TABLE DISCOUNT
(
	discount_id UNIQUEIDENTIFIER PRIMARY KEY,
	discount_percent INT CHECK(discount_percent > 0 AND discount_percent <= 100) NOT NULL,
	discount_begin DATE DEFAULT GETDATE(),
	discount_end DATE DEFAULT GETDATE(),
	discount_image VARCHAR(255) NULL
)

CREATE TABLE PRODUCT
(
	product_id UNIQUEIDENTIFIER PRIMARY KEY,
	product_code VARCHAR(20) NOT NULL,
	product_name NVARCHAR(110) NOT NULL,
	product_description NVARCHAR(max) NULL,
	product_quantity INT CHECK(product_quantity >= 0) DEFAULT 0,
	product_size VARCHAR(2) NOT NULL,
	product_color VARCHAR(10) NOT NULL,
	product_price INT CHECK(product_price > 0) NOT NULL,
	product_status BIT DEFAULT 1,
	category_id VARCHAR(10) REFERENCES CATEGORY(category_id) ON DELETE NO ACTION ON UPDATE CASCADE NOT NULL,
	discount_id UNIQUEIDENTIFIER REFERENCES DISCOUNT(discount_id) ON DELETE SET NULL ON UPDATE CASCADE NULL,
)

CREATE TABLE INVOICE
(
	invoice_id UNIQUEIDENTIFIER PRIMARY KEY,
	invoice_note NVARCHAR(255) NULL,
	invoice_address NVARCHAR(255) NOT NULL,
	invoice_date DATETIME DEFAULT GETDATE(),
	invoice_status BIT DEFAULT 0,
	invoice_shippingStatus BIT DEFAULT 0,
	user_phone VARCHAR(10) REFERENCES USERS(user_phone) ON DELETE NO ACTION ON UPDATE CASCADE NOT NULL
)

CREATE TABLE INVOICE_DETAIL
(
	invoice_id UNIQUEIDENTIFIER REFERENCES INVOICE(invoice_id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
	product_id UNIQUEIDENTIFIER REFERENCES PRODUCT(product_id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
	invoice_DT_price INT CHECK(invoice_DT_price > 0) DEFAULT 1,
	invoice_DT_quantity INT CHECK (invoice_DT_quantity > 0) NOT NULL
)

CREATE TABLE FEEDBACK 
(
	product_id UNIQUEIDENTIFIER REFERENCES PRODUCT(product_id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
	user_phone VARCHAR(10) REFERENCES USERS(user_phone) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
	feedback_content NVARCHAR(255) NOT NULL,
	feedback_date DATE DEFAULT GETDATE(),
	feedback_star TINYINT CHECK(feedback_star > 0 AND feedback_star <=5) NOT NULL,
	PRIMARY KEY(product_id,user_phone)
)

CREATE TABLE IMAGE
(
	image_id VARCHAR(255) PRIMARY KEY,
	product_id UNIQUEIDENTIFIER REFERENCES PRODUCT(product_id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
)

CREATE TABLE DETAIL
(
	detail_id UNIQUEIDENTIFIER PRIMARY KEY,
	detail_name NVARCHAR(20) NOT NULL,
	detail_value NVARCHAR(30) NOT NULL,
)

CREATE TABLE DETAIL_PRODUCT
(
product_id UNIQUEIDENTIFIER REFERENCES PRODUCT(product_id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
detail_id UNIQUEIDENTIFIER REFERENCES DETAIL(detail_id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
PRIMARY KEY(product_id,detail_id)
)